name: app

type: php:7.4

runtime:
    extensions:
        - apcu
        - mbstring
        - sodium
        - ctype
        - iconv
        - pdo_pgsql

relationships:
    db: "mydatabase:postgresql"
    redis: "myredis:redis"

#variables:
#    php:
#        # uncomment on PHP 7.4+
#        #opcache.preload: /app/config/preload.php

build:
    flavor: none

disk: 512

web:
    locations:
        "/":
            root: "public"
            expires: 1h
            passthru: "/index.php"



mounts:
    "/var": { source: local, source_path: var }

hooks:
    build: |
        set -x -e

        curl -s https://get.symfony.com/cloud/configurator | (>&2 bash)

        (>&2
            php-ext-install redis 5.3.1
            symfony-build
        )

    deploy: |
        set -x -e

        (>&2 symfony-deploy)
